import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import { CUSTOMER_PORTAL_INVOICE_PDF_THEME } from '@/app/administrator/invoices/invoicePdfTheme';
import { formatRouteDate } from '@/lib/routeDetailHelpers';
import {
  invoiceLabel,
  STAFF_VISIT_COLUMNS,
  VISIT_COLUMNS,
  VISIT_STATUS_LABELS,
  type PropertyGroup,
  type PropertyHistoryResult,
  type VisitRow,
} from '@/lib/propertyHistory';
import { resultProperties } from '@/lib/propertyHistoryReport';
import { titleCase } from '@/lib/propertyHistoryTypeahead';

export interface PropertyHistoryReportPdfInput {
  referenceNumber: string;
  organisation: { companyName: string; abn: string; phone: string; address: string };
  /** The Customer's name, or "All customers". */
  customerLabel: string;
  generatedBy: string;
  generatedAt: string;
  searchLabel: string;
  filterLabels: string[];
  counts: { propertyCount: number; visitCount: number };
  result: PropertyHistoryResult;
  /** Adds the staff-only columns; a customer's report never has them. */
  staff: boolean;
}

const { colors, fonts } = CUSTOMER_PORTAL_INVOICE_PDF_THEME;
const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const LEFT = 40;
const RIGHT = PAGE_WIDTH - 40;
const TOP = 40;
const CONTENT_BOTTOM = PAGE_HEIGHT - 60;
const FOOTER_Y = PAGE_HEIGHT - 30;

const TIMESTAMP = new Intl.DateTimeFormat('en-AU', {
  timeZone: 'Australia/Sydney',
  day: 'numeric',
  month: 'short',
  year: 'numeric',
  hour: 'numeric',
  minute: '2-digit',
  timeZoneName: 'short',
});

const plural = (count: number, one: string, many: string) => `${count} ${count === 1 ? one : many}`;

function visitCells(row: VisitRow, staff: boolean): string[] {
  const cells = [
    formatRouteDate(row.date),
    row.routeCode ?? row.routeId,
    row.agent || '—',
    row.auction ? 'Auction' : '—',
    String(row.signsPlaced),
    invoiceLabel(row.invoices),
    VISIT_STATUS_LABELS[row.status],
  ];
  if (!staff) return cells;
  return [
    ...cells,
    row.customerName ?? '—',
    row.operatorName ?? '—',
    row.missingSigns ? String(row.missingSigns) : '—',
    row.locationPrecision ? titleCase(row.locationPrecision) : '—',
  ];
}

/**
 * Renders a Property History Report (#291) on the server: a header naming who
 * it's for, who generated it, when, and the search, then the same groups as
 * the screen, and "Snapshot as at" on every page. Everything is plain text --
 * a report is handed to agents, so it carries no links into the portal.
 */
export function renderPropertyHistoryReportPdf(input: PropertyHistoryReportPdfInput): ArrayBuffer {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const generatedAt = TIMESTAMP.format(new Date(input.generatedAt));
  let y = TOP;

  const ensureSpace = (height: number) => {
    if (y + height <= CONTENT_BOTTOM) return;
    doc.addPage();
    y = TOP;
  };

  // Header band: the organisation's branding, the title and the reference.
  doc.setFillColor(...colors.header);
  doc.roundedRect(LEFT, y, RIGHT - LEFT, 76, 12, 12, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(fonts.large);
  doc.setTextColor(...colors.headerText);
  doc.text(input.organisation.companyName, LEFT + 20, y + 28);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fonts.small);
  doc.setTextColor(...colors.headerTextMuted);
  const contact = [input.organisation.abn, input.organisation.phone, input.organisation.address].filter(Boolean).join(' · ');
  doc.text(doc.splitTextToSize(contact, 260), LEFT + 20, y + 44);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(fonts.xlarge - 4);
  doc.setTextColor(...colors.headerText);
  doc.text('Property History Report', RIGHT - 20, y + 32, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fonts.small);
  doc.setTextColor(...colors.headerTextMuted);
  doc.text(input.referenceNumber, RIGHT - 20, y + 48, { align: 'right' });
  y += 76 + 24;

  // What the report covers.
  const details: Array<[string, string]> = [
    ['Customer', input.customerLabel],
    ['Search', input.searchLabel],
    ['Filters', input.filterLabels.join(' · ')],
    ['Found', `${plural(input.counts.propertyCount, 'Property', 'Properties')} · ${plural(input.counts.visitCount, 'Visit', 'Visits')}`],
    ['Generated by', input.generatedBy],
    ['Generated', generatedAt],
    ['Reference', input.referenceNumber],
  ];
  doc.setFontSize(fonts.default);
  for (const [label, value] of details) {
    const lines = doc.splitTextToSize(value, RIGHT - LEFT - 90);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.labelMuted);
    doc.text(label, LEFT, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.text);
    doc.text(lines, LEFT + 90, y);
    y += lines.length * 13 + 3;
  }
  y += 12;

  const columns = [...VISIT_COLUMNS, ...(input.staff ? STAFF_VISIT_COLUMNS : [])];
  const visitTable = (rows: VisitRow[]) => {
    autoTable(doc, {
      startY: y,
      head: [columns],
      body: rows.map((row) => visitCells(row, input.staff)),
      theme: 'plain',
      margin: { left: LEFT, right: PAGE_WIDTH - RIGHT, top: TOP, bottom: PAGE_HEIGHT - CONTENT_BOTTOM },
      styles: { font: 'helvetica', fontSize: input.staff ? fonts.label - 1 : fonts.label, textColor: colors.text, lineColor: colors.hairline, lineWidth: { bottom: 0.6 } },
      headStyles: { textColor: colors.bodyMuted, fontStyle: 'bold', lineWidth: { bottom: 1 }, lineColor: colors.header },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  };

  const heading = (text: string, size: number, color: [number, number, number]) => {
    ensureSpace(size + 40);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(size);
    doc.setTextColor(...color);
    doc.text(text, LEFT, y);
    y += size + 6;
  };

  const propertySection = (property: PropertyGroup) => {
    heading(`${property.address} — ${plural(property.visitCount, 'Visit', 'Visits')}`, fonts.default, colors.header);
    if (property.visits.length > 0) visitTable(property.visits);
    if (property.scheduled.length > 0) {
      heading('Scheduled', fonts.small, colors.bodyMuted);
      visitTable(property.scheduled);
    }
    y += 6;
  };

  if (resultProperties(input.result).length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(fonts.default);
    doc.setTextColor(...colors.bodyMuted);
    doc.text('No Visits match this search.', LEFT, y);
  } else if (input.result.level === 'suburb') {
    for (const street of input.result.streets) {
      heading(`${titleCase(street.street)} — ${plural(street.properties.length, 'Property', 'Properties')}`, fonts.medium, colors.brandText);
      street.properties.forEach(propertySection);
    }
  } else {
    resultProperties(input.result).forEach(propertySection);
  }

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...colors.border);
    doc.setLineWidth(0.6);
    doc.line(LEFT, FOOTER_Y - 12, RIGHT, FOOTER_Y - 12);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(fonts.small);
    doc.setTextColor(...colors.labelMuted);
    doc.text(`Snapshot as at ${generatedAt}`, LEFT, FOOTER_Y);
    doc.text(`${input.referenceNumber} · Page ${page} of ${pages}`, RIGHT, FOOTER_Y, { align: 'right' });
  }

  return doc.output('arraybuffer');
}
