import outputs from '@/amplify_outputs.json';

/**
 * Deploy-time values that amplify/backend.ts bakes into amplify_outputs.json's
 * `custom` section via `backend.addOutput({ custom: { ... } })`.
 *
 * This exists because `process.env.AWS_BRANCH` / `AMPLIFY_BRANCH` are only
 * populated during the CDK synth/build step -- they are NOT available in the
 * deployed Next.js SSR runtime. Code that tried to reconstruct a branch-scoped
 * SES template name from those env vars at runtime silently fell back to the
 * un-suffixed template name and broke sends (TemplateDoesNotExistException).
 * Reading the name back out of amplify_outputs.json instead uses the value
 * amplify/backend.ts actually deployed, computed when AWS_BRANCH was real.
 *
 * amplify_outputs.json is untyped JSON with no `custom` field in the local
 * placeholder generated by `npm run generate:config`, hence the cast.
 */
export interface AmplifyOutputsCustom {
  sesInvoiceTemplateName?: string;
  sesInvitationTemplateName?: string;
  sesStaffInvitationTemplateName?: string;
}

export const customOutputs: AmplifyOutputsCustom =
  (outputs as { custom?: AmplifyOutputsCustom }).custom || {};
